version: 2
jobs:
  go1.20: &base
    docker:
      - image: cimg/go:1.20
    steps:
      - run: go version
      - checkout
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)

  go1.19: &base_next
    <<: *base
    docker:
      - image: cimg/go:1.19
    steps:
      - run: go version
      - checkout
      - run: go test -race -v ./...

  go1.18:
    <<: *base_next
    docker:
      - image: cimg/go:1.18

workflows:
  version: 2
  build:
    jobs:
      - go1.20
      - go1.19
      - go1.18
